apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
        - name: cron
          image: wassimkha/cron-service:latest

---
apiVersion: v1
kind: Service
metadata:
  name: cron-srv
spec:
  selector:
    app: cron
  ports:
    - name: cron
      protocol: TCP
      port: 3000
      targetPort: 3000